language: java
sudo: false
cache:
  directories:
  - $HOME/.m2
install:
  - echo "Skip"
jdk:
  - oraclejdk8
script:
  - ./mvnw -Dsurefire.useFile=false clean verify

after_success:
  - bash <(curl -s https://codecov.io/bash)
